/*
 * generated by Xtext 2.12.0
 */
package biochemsimulation.reactionrules.ide.contentassist.antlr;

import biochemsimulation.reactionrules.ide.contentassist.antlr.internal.InternalReactionRulesParser;
import biochemsimulation.reactionrules.services.ReactionRulesGrammarAccess;
import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ReactionRulesParser extends AbstractContentAssistParser {

	@Inject
	private ReactionRulesGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalReactionRulesParser createParser() {
		InternalReactionRulesParser result = new InternalReactionRulesParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelLocationAccess().getAlternatives(), "rule__ModelLocation__Alternatives");
					put(grammarAccess.getReactionPropertyAccess().getAlternatives(), "rule__ReactionProperty__Alternatives");
					put(grammarAccess.getArithmeticTypeAccess().getAlternatives(), "rule__ArithmeticType__Alternatives");
					put(grammarAccess.getVariableAccess().getAlternatives(), "rule__Variable__Alternatives");
					put(grammarAccess.getLinkStateAccess().getLinkStateAlternatives_1_0(), "rule__LinkState__LinkStateAlternatives_1_0");
					put(grammarAccess.getPatternAssignmentAccess().getAlternatives(), "rule__PatternAssignment__Alternatives");
					put(grammarAccess.getRuleBodyAccess().getAlternatives(), "rule__RuleBody__Alternatives");
					put(grammarAccess.getReactionRuleModelAccess().getGroup(), "rule__ReactionRuleModel__Group__0");
					put(grammarAccess.getModelUriAccess().getGroup(), "rule__ModelUri__Group__0");
					put(grammarAccess.getModelPathAccess().getGroup(), "rule__ModelPath__Group__0");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getReactionContainerAccess().getGroup(), "rule__ReactionContainer__Group__0");
					put(grammarAccess.getAgentInstanceSiteStateAccess().getGroup(), "rule__AgentInstanceSiteState__Group__0");
					put(grammarAccess.getAgentInstanceLinkStateAccess().getGroup(), "rule__AgentInstanceLinkState__Group__0");
					put(grammarAccess.getAgentInstanceAccess().getGroup(), "rule__AgentInstance__Group__0");
					put(grammarAccess.getFloatAccess().getGroup(), "rule__Float__Group__0");
					put(grammarAccess.getScientificFloatAccess().getGroup(), "rule__ScientificFloat__Group__0");
					put(grammarAccess.getSignedIntegerAccess().getGroup(), "rule__SignedInteger__Group__0");
					put(grammarAccess.getStatesAccess().getGroup(), "rule__States__Group__0");
					put(grammarAccess.getStatesAccess().getGroup_1(), "rule__States__Group_1__0");
					put(grammarAccess.getStatesAccess().getGroup_1_2(), "rule__States__Group_1_2__0");
					put(grammarAccess.getSiteAccess().getGroup(), "rule__Site__Group__0");
					put(grammarAccess.getSitesAccess().getGroup(), "rule__Sites__Group__0");
					put(grammarAccess.getSitesAccess().getGroup_1(), "rule__Sites__Group_1__0");
					put(grammarAccess.getSitesAccess().getGroup_1_2(), "rule__Sites__Group_1_2__0");
					put(grammarAccess.getAgentAccess().getGroup(), "rule__Agent__Group__0");
					put(grammarAccess.getPatternVariableAccess().getGroup(), "rule__PatternVariable__Group__0");
					put(grammarAccess.getArithmeticVariableAccess().getGroup(), "rule__ArithmeticVariable__Group__0");
					put(grammarAccess.getSemiLinkAccess().getGroup(), "rule__SemiLink__Group__0");
					put(grammarAccess.getFreeLinkAccess().getGroup(), "rule__FreeLink__Group__0");
					put(grammarAccess.getWhatEverAccess().getGroup(), "rule__WhatEver__Group__0");
					put(grammarAccess.getLimitLinkAccess().getGroup(), "rule__LimitLink__Group__0");
					put(grammarAccess.getExactLinkAgentAccess().getGroup(), "rule__ExactLinkAgent__Group__0");
					put(grammarAccess.getExactLinkSiteAccess().getGroup(), "rule__ExactLinkSite__Group__0");
					put(grammarAccess.getExactLinkAccess().getGroup(), "rule__ExactLink__Group__0");
					put(grammarAccess.getSiteStateAccess().getGroup(), "rule__SiteState__Group__0");
					put(grammarAccess.getLinkStateAccess().getGroup(), "rule__LinkState__Group__0");
					put(grammarAccess.getSitePatternAccess().getGroup(), "rule__SitePattern__Group__0");
					put(grammarAccess.getSitePatternAccess().getGroup_2(), "rule__SitePattern__Group_2__0");
					put(grammarAccess.getSitePatternAccess().getGroup_3(), "rule__SitePattern__Group_3__0");
					put(grammarAccess.getSitePatternsAccess().getGroup(), "rule__SitePatterns__Group__0");
					put(grammarAccess.getSitePatternsAccess().getGroup_1(), "rule__SitePatterns__Group_1__0");
					put(grammarAccess.getSitePatternsAccess().getGroup_1_1(), "rule__SitePatterns__Group_1_1__0");
					put(grammarAccess.getAgentPatternAccess().getGroup(), "rule__AgentPattern__Group__0");
					put(grammarAccess.getPatternAccess().getGroup(), "rule__Pattern__Group__0");
					put(grammarAccess.getPatternAccess().getGroup_2(), "rule__Pattern__Group_2__0");
					put(grammarAccess.getPatternAccess().getGroup_2_1(), "rule__Pattern__Group_2_1__0");
					put(grammarAccess.getObservationAccess().getGroup(), "rule__Observation__Group__0");
					put(grammarAccess.getInitialAccess().getGroup(), "rule__Initial__Group__0");
					put(grammarAccess.getRuleVariablesAccess().getGroup(), "rule__RuleVariables__Group__0");
					put(grammarAccess.getRuleVariablesAccess().getGroup_1(), "rule__RuleVariables__Group_1__0");
					put(grammarAccess.getUnidirectionalRuleAccess().getGroup(), "rule__UnidirectionalRule__Group__0");
					put(grammarAccess.getBidirectionalRuleAccess().getGroup(), "rule__BidirectionalRule__Group__0");
					put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
					put(grammarAccess.getReactionRuleModelAccess().getModelAssignment_0(), "rule__ReactionRuleModel__ModelAssignment_0");
					put(grammarAccess.getReactionRuleModelAccess().getReationContainerAssignment_1(), "rule__ReactionRuleModel__ReationContainerAssignment_1");
					put(grammarAccess.getReactionRuleModelAccess().getReactionPropertiesAssignment_2(), "rule__ReactionRuleModel__ReactionPropertiesAssignment_2");
					put(grammarAccess.getModelUriAccess().getUriAssignment_1(), "rule__ModelUri__UriAssignment_1");
					put(grammarAccess.getModelPathAccess().getPathAssignment_1(), "rule__ModelPath__PathAssignment_1");
					put(grammarAccess.getModelAccess().getNameAssignment_1(), "rule__Model__NameAssignment_1");
					put(grammarAccess.getModelAccess().getLocationAssignment_2(), "rule__Model__LocationAssignment_2");
					put(grammarAccess.getReactionContainerAccess().getAgentInstancesAssignment_1(), "rule__ReactionContainer__AgentInstancesAssignment_1");
					put(grammarAccess.getAgentInstanceSiteStateAccess().getSiteAssignment_0(), "rule__AgentInstanceSiteState__SiteAssignment_0");
					put(grammarAccess.getAgentInstanceSiteStateAccess().getSiteStateAssignment_1(), "rule__AgentInstanceSiteState__SiteStateAssignment_1");
					put(grammarAccess.getAgentInstanceLinkStateAccess().getSiteAssignment_0(), "rule__AgentInstanceLinkState__SiteAssignment_0");
					put(grammarAccess.getAgentInstanceLinkStateAccess().getLinkStateAssignment_1(), "rule__AgentInstanceLinkState__LinkStateAssignment_1");
					put(grammarAccess.getAgentInstanceAccess().getNameAssignment_1(), "rule__AgentInstance__NameAssignment_1");
					put(grammarAccess.getAgentInstanceAccess().getAgentAssignment_2(), "rule__AgentInstance__AgentAssignment_2");
					put(grammarAccess.getAgentInstanceAccess().getSiteStatesAssignment_3(), "rule__AgentInstance__SiteStatesAssignment_3");
					put(grammarAccess.getAgentInstanceAccess().getLinkStatesAssignment_4(), "rule__AgentInstance__LinkStatesAssignment_4");
					put(grammarAccess.getArithmeticValueAccess().getValueAssignment(), "rule__ArithmeticValue__ValueAssignment");
					put(grammarAccess.getStateAccess().getNameAssignment(), "rule__State__NameAssignment");
					put(grammarAccess.getStatesAccess().getStateAssignment_1_1(), "rule__States__StateAssignment_1_1");
					put(grammarAccess.getStatesAccess().getStateAssignment_1_2_1(), "rule__States__StateAssignment_1_2_1");
					put(grammarAccess.getSiteAccess().getNameAssignment_0(), "rule__Site__NameAssignment_0");
					put(grammarAccess.getSiteAccess().getStatesAssignment_1(), "rule__Site__StatesAssignment_1");
					put(grammarAccess.getSitesAccess().getSitesAssignment_1_1(), "rule__Sites__SitesAssignment_1_1");
					put(grammarAccess.getSitesAccess().getSitesAssignment_1_2_1(), "rule__Sites__SitesAssignment_1_2_1");
					put(grammarAccess.getAgentAccess().getNameAssignment_1(), "rule__Agent__NameAssignment_1");
					put(grammarAccess.getAgentAccess().getSitesAssignment_2(), "rule__Agent__SitesAssignment_2");
					put(grammarAccess.getPatternVariableAccess().getNameAssignment_1(), "rule__PatternVariable__NameAssignment_1");
					put(grammarAccess.getPatternVariableAccess().getPatternAssignment_3(), "rule__PatternVariable__PatternAssignment_3");
					put(grammarAccess.getArithmeticVariableAccess().getNameAssignment_1(), "rule__ArithmeticVariable__NameAssignment_1");
					put(grammarAccess.getArithmeticVariableAccess().getValueAssignment_3(), "rule__ArithmeticVariable__ValueAssignment_3");
					put(grammarAccess.getSemiLinkAccess().getNameAssignment_1(), "rule__SemiLink__NameAssignment_1");
					put(grammarAccess.getFreeLinkAccess().getNameAssignment_1(), "rule__FreeLink__NameAssignment_1");
					put(grammarAccess.getWhatEverAccess().getNameAssignment_1(), "rule__WhatEver__NameAssignment_1");
					put(grammarAccess.getLimitLinkAccess().getStateAssignment_1(), "rule__LimitLink__StateAssignment_1");
					put(grammarAccess.getExactLinkAgentAccess().getAgentAssignment_1(), "rule__ExactLinkAgent__AgentAssignment_1");
					put(grammarAccess.getExactLinkSiteAccess().getSiteAssignment_1(), "rule__ExactLinkSite__SiteAssignment_1");
					put(grammarAccess.getExactLinkAccess().getLinkAgentAssignment_1(), "rule__ExactLink__LinkAgentAssignment_1");
					put(grammarAccess.getExactLinkAccess().getLinkSiteAssignment_3(), "rule__ExactLink__LinkSiteAssignment_3");
					put(grammarAccess.getSiteStateAccess().getStateAssignment_1(), "rule__SiteState__StateAssignment_1");
					put(grammarAccess.getLinkStateAccess().getLinkStateAssignment_1(), "rule__LinkState__LinkStateAssignment_1");
					put(grammarAccess.getSitePatternAccess().getSiteAssignment_1(), "rule__SitePattern__SiteAssignment_1");
					put(grammarAccess.getSitePatternAccess().getStateAssignment_2_1(), "rule__SitePattern__StateAssignment_2_1");
					put(grammarAccess.getSitePatternAccess().getLinkStateAssignment_3_1(), "rule__SitePattern__LinkStateAssignment_3_1");
					put(grammarAccess.getSitePatternsAccess().getSitePatternsAssignment_1_0(), "rule__SitePatterns__SitePatternsAssignment_1_0");
					put(grammarAccess.getSitePatternsAccess().getSitePatternsAssignment_1_1_1(), "rule__SitePatterns__SitePatternsAssignment_1_1_1");
					put(grammarAccess.getAgentPatternAccess().getAgentAssignment_1(), "rule__AgentPattern__AgentAssignment_1");
					put(grammarAccess.getAgentPatternAccess().getSitePatternsAssignment_3(), "rule__AgentPattern__SitePatternsAssignment_3");
					put(grammarAccess.getPatternAccess().getAgentPatternsAssignment_2_0(), "rule__Pattern__AgentPatternsAssignment_2_0");
					put(grammarAccess.getPatternAccess().getAgentPatternsAssignment_2_1_1(), "rule__Pattern__AgentPatternsAssignment_2_1_1");
					put(grammarAccess.getObservationAccess().getNameAssignment_1(), "rule__Observation__NameAssignment_1");
					put(grammarAccess.getObservationAccess().getObservationPatternAssignment_2(), "rule__Observation__ObservationPatternAssignment_2");
					put(grammarAccess.getInitialAccess().getNameAssignment_1(), "rule__Initial__NameAssignment_1");
					put(grammarAccess.getInitialAccess().getCountAssignment_2(), "rule__Initial__CountAssignment_2");
					put(grammarAccess.getInitialAccess().getInitialPatternAssignment_3(), "rule__Initial__InitialPatternAssignment_3");
					put(grammarAccess.getAssignFromPatternAccess().getPatternAssignment(), "rule__AssignFromPattern__PatternAssignment");
					put(grammarAccess.getAssignFromVariableAccess().getPatternVarAssignment(), "rule__AssignFromVariable__PatternVarAssignment");
					put(grammarAccess.getRuleVariablesAccess().getVariablesAssignment_0(), "rule__RuleVariables__VariablesAssignment_0");
					put(grammarAccess.getRuleVariablesAccess().getVariablesAssignment_1_1(), "rule__RuleVariables__VariablesAssignment_1_1");
					put(grammarAccess.getUnidirectionalRuleAccess().getLhsAssignment_0(), "rule__UnidirectionalRule__LhsAssignment_0");
					put(grammarAccess.getUnidirectionalRuleAccess().getOperatorAssignment_1(), "rule__UnidirectionalRule__OperatorAssignment_1");
					put(grammarAccess.getUnidirectionalRuleAccess().getRhsAssignment_2(), "rule__UnidirectionalRule__RhsAssignment_2");
					put(grammarAccess.getUnidirectionalRuleAccess().getVariablesAssignment_5(), "rule__UnidirectionalRule__VariablesAssignment_5");
					put(grammarAccess.getBidirectionalRuleAccess().getLhsAssignment_0(), "rule__BidirectionalRule__LhsAssignment_0");
					put(grammarAccess.getBidirectionalRuleAccess().getOperatorAssignment_1(), "rule__BidirectionalRule__OperatorAssignment_1");
					put(grammarAccess.getBidirectionalRuleAccess().getRhsAssignment_2(), "rule__BidirectionalRule__RhsAssignment_2");
					put(grammarAccess.getBidirectionalRuleAccess().getVariablesAssignment_5(), "rule__BidirectionalRule__VariablesAssignment_5");
					put(grammarAccess.getRuleAccess().getNameAssignment_1(), "rule__Rule__NameAssignment_1");
					put(grammarAccess.getRuleAccess().getRuleAssignment_2(), "rule__Rule__RuleAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ReactionRulesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ReactionRulesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
