/**
 * generated by Xtext 2.16.0
 */
package org.simsg.simsgl.ide;

import com.google.inject.Injector;
import org.simsg.simsgl.SimSGLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SimSGLIdeSetup extends SimSGLStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from SimSGLRuntimeModule to Module");
  }
}
