/*
 * generated by Xtext 2.12.0
 */
package biochemsimulation.reactionrules


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ReactionRulesStandaloneSetup extends ReactionRulesStandaloneSetupGenerated {

	def static void doSetup() {
		new ReactionRulesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
