/**
 * generated by Xtext 2.16.0
 */
package org.simsg.simsgl.simSGL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Agent Pattern</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.simsg.simsgl.simSGL.SimSGLPackage#getAgentPattern()
 * @model
 * @generated
 */
public interface AgentPattern extends EObject
{
} // AgentPattern
