/**
 * generated by Xtext 2.16.0
 */
package org.simsg.simsgl.simSGL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Site Pattern</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.simsg.simsgl.simSGL.SingleSitePattern#getSite <em>Site</em>}</li>
 *   <li>{@link org.simsg.simsgl.simSGL.SingleSitePattern#getLinkState <em>Link State</em>}</li>
 * </ul>
 *
 * @see org.simsg.simsgl.simSGL.SimSGLPackage#getSingleSitePattern()
 * @model
 * @generated
 */
public interface SingleSitePattern extends SitePattern
{
  /**
   * Returns the value of the '<em><b>Site</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Site</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Site</em>' reference.
   * @see #setSite(SingleSite)
   * @see org.simsg.simsgl.simSGL.SimSGLPackage#getSingleSitePattern_Site()
   * @model
   * @generated
   */
  SingleSite getSite();

  /**
   * Sets the value of the '{@link org.simsg.simsgl.simSGL.SingleSitePattern#getSite <em>Site</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Site</em>' reference.
   * @see #getSite()
   * @generated
   */
  void setSite(SingleSite value);

  /**
   * Returns the value of the '<em><b>Link State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Link State</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link State</em>' containment reference.
   * @see #setLinkState(LinkState)
   * @see org.simsg.simsgl.simSGL.SimSGLPackage#getSingleSitePattern_LinkState()
   * @model containment="true"
   * @generated
   */
  LinkState getLinkState();

  /**
   * Sets the value of the '{@link org.simsg.simsgl.simSGL.SingleSitePattern#getLinkState <em>Link State</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link State</em>' containment reference.
   * @see #getLinkState()
   * @generated
   */
  void setLinkState(LinkState value);

} // SingleSitePattern
