/**
 * generated by Xtext 2.16.0
 */
package org.simsg.simsgl.simSGL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.simsg.simsgl.simSGL.SimSGLPackage#getVariable()
 * @model
 * @generated
 */
public interface Variable extends SimSGLProperty
{
} // Variable
