/**
 * generated by Xtext 2.16.0
 */
package org.simsg.simsgl.simSGL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.simsg.simsgl.simSGL.Agent;
import org.simsg.simsgl.simSGL.SimSGLPackage;
import org.simsg.simsgl.simSGL.Sites;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Agent</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.simsg.simsgl.simSGL.impl.AgentImpl#getSites <em>Sites</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AgentImpl extends SimSGLPropertyImpl implements Agent
{
  /**
   * The cached value of the '{@link #getSites() <em>Sites</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSites()
   * @generated
   * @ordered
   */
  protected Sites sites;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AgentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SimSGLPackage.Literals.AGENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Sites getSites()
  {
    return sites;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSites(Sites newSites, NotificationChain msgs)
  {
    Sites oldSites = sites;
    sites = newSites;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SimSGLPackage.AGENT__SITES, oldSites, newSites);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSites(Sites newSites)
  {
    if (newSites != sites)
    {
      NotificationChain msgs = null;
      if (sites != null)
        msgs = ((InternalEObject)sites).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SimSGLPackage.AGENT__SITES, null, msgs);
      if (newSites != null)
        msgs = ((InternalEObject)newSites).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SimSGLPackage.AGENT__SITES, null, msgs);
      msgs = basicSetSites(newSites, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimSGLPackage.AGENT__SITES, newSites, newSites));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SimSGLPackage.AGENT__SITES:
        return basicSetSites(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SimSGLPackage.AGENT__SITES:
        return getSites();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SimSGLPackage.AGENT__SITES:
        setSites((Sites)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SimSGLPackage.AGENT__SITES:
        setSites((Sites)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SimSGLPackage.AGENT__SITES:
        return sites != null;
    }
    return super.eIsSet(featureID);
  }

} //AgentImpl
