/**
 * generated by Xtext 2.16.0
 */
package org.simsg.simsgl.simSGL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.simsg.simsgl.simSGL.LinkState;
import org.simsg.simsgl.simSGL.MultiLinkState;
import org.simsg.simsgl.simSGL.SimSGLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Multi Link State</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.simsg.simsgl.simSGL.impl.MultiLinkStateImpl#getLinkState <em>Link State</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MultiLinkStateImpl extends MinimalEObjectImpl.Container implements MultiLinkState
{
  /**
   * The cached value of the '{@link #getLinkState() <em>Link State</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLinkState()
   * @generated
   * @ordered
   */
  protected LinkState linkState;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MultiLinkStateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SimSGLPackage.Literals.MULTI_LINK_STATE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LinkState getLinkState()
  {
    return linkState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLinkState(LinkState newLinkState, NotificationChain msgs)
  {
    LinkState oldLinkState = linkState;
    linkState = newLinkState;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SimSGLPackage.MULTI_LINK_STATE__LINK_STATE, oldLinkState, newLinkState);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLinkState(LinkState newLinkState)
  {
    if (newLinkState != linkState)
    {
      NotificationChain msgs = null;
      if (linkState != null)
        msgs = ((InternalEObject)linkState).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SimSGLPackage.MULTI_LINK_STATE__LINK_STATE, null, msgs);
      if (newLinkState != null)
        msgs = ((InternalEObject)newLinkState).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SimSGLPackage.MULTI_LINK_STATE__LINK_STATE, null, msgs);
      msgs = basicSetLinkState(newLinkState, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimSGLPackage.MULTI_LINK_STATE__LINK_STATE, newLinkState, newLinkState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SimSGLPackage.MULTI_LINK_STATE__LINK_STATE:
        return basicSetLinkState(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SimSGLPackage.MULTI_LINK_STATE__LINK_STATE:
        return getLinkState();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SimSGLPackage.MULTI_LINK_STATE__LINK_STATE:
        setLinkState((LinkState)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SimSGLPackage.MULTI_LINK_STATE__LINK_STATE:
        setLinkState((LinkState)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SimSGLPackage.MULTI_LINK_STATE__LINK_STATE:
        return linkState != null;
    }
    return super.eIsSet(featureID);
  }

} //MultiLinkStateImpl
