/**
 * generated by Xtext 2.16.0
 */
package org.simsg.simsgl.simSGL.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.simsg.simsgl.simSGL.Agent;
import org.simsg.simsgl.simSGL.AgentPattern;
import org.simsg.simsgl.simSGL.ArithmeticValue;
import org.simsg.simsgl.simSGL.ArithmeticVariable;
import org.simsg.simsgl.simSGL.AssignFromPattern;
import org.simsg.simsgl.simSGL.AssignFromVariable;
import org.simsg.simsgl.simSGL.BoundAnyLink;
import org.simsg.simsgl.simSGL.BoundAnyOfTypeLink;
import org.simsg.simsgl.simSGL.BoundAnyOfTypeLinkAgent;
import org.simsg.simsgl.simSGL.BoundAnyOfTypeLinkSite;
import org.simsg.simsgl.simSGL.BoundLink;
import org.simsg.simsgl.simSGL.FreeLink;
import org.simsg.simsgl.simSGL.IndexedFreeLink;
import org.simsg.simsgl.simSGL.Initial;
import org.simsg.simsgl.simSGL.Iterations;
import org.simsg.simsgl.simSGL.LinkState;
import org.simsg.simsgl.simSGL.Model;
import org.simsg.simsgl.simSGL.MultiLink;
import org.simsg.simsgl.simSGL.MultiLinkSitePattern;
import org.simsg.simsgl.simSGL.MultiLinkState;
import org.simsg.simsgl.simSGL.MultiSite;
import org.simsg.simsgl.simSGL.NumericAssignment;
import org.simsg.simsgl.simSGL.NumericFromLiteral;
import org.simsg.simsgl.simSGL.NumericFromVariable;
import org.simsg.simsgl.simSGL.Observation;
import org.simsg.simsgl.simSGL.Pattern;
import org.simsg.simsgl.simSGL.PatternAssignment;
import org.simsg.simsgl.simSGL.PatternVariable;
import org.simsg.simsgl.simSGL.Population;
import org.simsg.simsgl.simSGL.Rule;
import org.simsg.simsgl.simSGL.RuleBody;
import org.simsg.simsgl.simSGL.RuleVariables;
import org.simsg.simsgl.simSGL.SimSGLFactory;
import org.simsg.simsgl.simSGL.SimSGLModel;
import org.simsg.simsgl.simSGL.SimSGLPackage;
import org.simsg.simsgl.simSGL.SimSGLProperty;
import org.simsg.simsgl.simSGL.SingleSite;
import org.simsg.simsgl.simSGL.SingleSitePattern;
import org.simsg.simsgl.simSGL.Site;
import org.simsg.simsgl.simSGL.SitePattern;
import org.simsg.simsgl.simSGL.SitePatterns;
import org.simsg.simsgl.simSGL.SiteState;
import org.simsg.simsgl.simSGL.Sites;
import org.simsg.simsgl.simSGL.State;
import org.simsg.simsgl.simSGL.States;
import org.simsg.simsgl.simSGL.Terminate;
import org.simsg.simsgl.simSGL.TerminationCondition;
import org.simsg.simsgl.simSGL.Time;
import org.simsg.simsgl.simSGL.TypedFreeLink;
import org.simsg.simsgl.simSGL.ValidAgentPattern;
import org.simsg.simsgl.simSGL.Variable;
import org.simsg.simsgl.simSGL.VoidAgentPattern;
import org.simsg.simsgl.simSGL.WhatEver;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class SimSGLPackageImpl extends EPackageImpl implements SimSGLPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass simSGLModelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass simSGLPropertyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass arithmeticValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass statesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass siteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass sitesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass agentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass patternVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass arithmeticVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass variableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass linkStateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass boundAnyOfTypeLinkAgentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass boundAnyOfTypeLinkSiteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass siteStateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiLinkStateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass sitePatternEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass sitePatternsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass validAgentPatternEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass voidAgentPatternEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass agentPatternEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass patternEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass observationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass numericFromLiteralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass numericFromVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass numericAssignmentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass initialEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass assignFromPatternEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass assignFromVariableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass patternAssignmentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ruleVariablesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ruleBodyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ruleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass iterationsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass timeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass populationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass terminationConditionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass terminateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass singleSiteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiSiteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass boundAnyLinkEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass freeLinkEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass indexedFreeLinkEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass typedFreeLinkEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass whatEverEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass boundLinkEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiLinkEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass boundAnyOfTypeLinkEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass singleSitePatternEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiLinkSitePatternEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.simsg.simsgl.simSGL.SimSGLPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private SimSGLPackageImpl()
  {
    super(eNS_URI, SimSGLFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link SimSGLPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static SimSGLPackage init()
  {
    if (isInited) return (SimSGLPackage)EPackage.Registry.INSTANCE.getEPackage(SimSGLPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredSimSGLPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    SimSGLPackageImpl theSimSGLPackage = registeredSimSGLPackage instanceof SimSGLPackageImpl ? (SimSGLPackageImpl)registeredSimSGLPackage : new SimSGLPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theSimSGLPackage.createPackageContents();

    // Initialize created meta-data
    theSimSGLPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theSimSGLPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(SimSGLPackage.eNS_URI, theSimSGLPackage);
    return theSimSGLPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSimSGLModel()
  {
    return simSGLModelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSimSGLModel_Model()
  {
    return (EReference)simSGLModelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSimSGLModel_Properties()
  {
    return (EReference)simSGLModelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getModel_Name()
  {
    return (EAttribute)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSimSGLProperty()
  {
    return simSGLPropertyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSimSGLProperty_Name()
  {
    return (EAttribute)simSGLPropertyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getArithmeticValue()
  {
    return arithmeticValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getArithmeticValue_Value()
  {
    return (EAttribute)arithmeticValueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getState()
  {
    return stateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getState_Name()
  {
    return (EAttribute)stateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getStates()
  {
    return statesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getStates_State()
  {
    return (EReference)statesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSite()
  {
    return siteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSite_Name()
  {
    return (EAttribute)siteEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSite_States()
  {
    return (EReference)siteEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSites()
  {
    return sitesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSites_Sites()
  {
    return (EReference)sitesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAgent()
  {
    return agentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAgent_Sites()
  {
    return (EReference)agentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPatternVariable()
  {
    return patternVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPatternVariable_Pattern()
  {
    return (EReference)patternVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getArithmeticVariable()
  {
    return arithmeticVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getArithmeticVariable_Value()
  {
    return (EReference)arithmeticVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getVariable()
  {
    return variableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getLinkState()
  {
    return linkStateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getLinkState_LinkState()
  {
    return (EReference)linkStateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBoundAnyOfTypeLinkAgent()
  {
    return boundAnyOfTypeLinkAgentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBoundAnyOfTypeLinkAgent_Agent()
  {
    return (EReference)boundAnyOfTypeLinkAgentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBoundAnyOfTypeLinkSite()
  {
    return boundAnyOfTypeLinkSiteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBoundAnyOfTypeLinkSite_Site()
  {
    return (EReference)boundAnyOfTypeLinkSiteEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSiteState()
  {
    return siteStateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSiteState_State()
  {
    return (EReference)siteStateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMultiLinkState()
  {
    return multiLinkStateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMultiLinkState_LinkState()
  {
    return (EReference)multiLinkStateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSitePattern()
  {
    return sitePatternEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSitePattern_State()
  {
    return (EReference)sitePatternEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSitePatterns()
  {
    return sitePatternsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSitePatterns_SitePatterns()
  {
    return (EReference)sitePatternsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getValidAgentPattern()
  {
    return validAgentPatternEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getValidAgentPattern_Agent()
  {
    return (EReference)validAgentPatternEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getValidAgentPattern_SitePatterns()
  {
    return (EReference)validAgentPatternEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getVoidAgentPattern()
  {
    return voidAgentPatternEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getVoidAgentPattern_Pattern()
  {
    return (EAttribute)voidAgentPatternEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAgentPattern()
  {
    return agentPatternEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPattern()
  {
    return patternEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPattern_AgentPatterns()
  {
    return (EReference)patternEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getObservation()
  {
    return observationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getObservation_ObservationPattern()
  {
    return (EReference)observationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getNumericFromLiteral()
  {
    return numericFromLiteralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getNumericFromLiteral_Value()
  {
    return (EReference)numericFromLiteralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getNumericFromVariable()
  {
    return numericFromVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getNumericFromVariable_ValueVar()
  {
    return (EReference)numericFromVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getNumericAssignment()
  {
    return numericAssignmentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getInitial()
  {
    return initialEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getInitial_Count()
  {
    return (EReference)initialEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getInitial_InitialPattern()
  {
    return (EReference)initialEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAssignFromPattern()
  {
    return assignFromPatternEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAssignFromPattern_Pattern()
  {
    return (EReference)assignFromPatternEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAssignFromVariable()
  {
    return assignFromVariableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAssignFromVariable_PatternVar()
  {
    return (EReference)assignFromVariableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPatternAssignment()
  {
    return patternAssignmentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRuleVariables()
  {
    return ruleVariablesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRuleVariables_Variables()
  {
    return (EReference)ruleVariablesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRuleBody()
  {
    return ruleBodyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRuleBody_Lhs()
  {
    return (EReference)ruleBodyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRuleBody_Operator()
  {
    return (EAttribute)ruleBodyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRuleBody_Rhs()
  {
    return (EReference)ruleBodyEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRuleBody_Variables()
  {
    return (EReference)ruleBodyEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRule()
  {
    return ruleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRule_Rule()
  {
    return (EReference)ruleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getIterations()
  {
    return iterationsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTime()
  {
    return timeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPopulation()
  {
    return populationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPopulation_Pa()
  {
    return (EReference)populationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTerminationCondition()
  {
    return terminationConditionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTerminationCondition_Value()
  {
    return (EAttribute)terminationConditionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTerminate()
  {
    return terminateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTerminate_Condition()
  {
    return (EReference)terminateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSingleSite()
  {
    return singleSiteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMultiSite()
  {
    return multiSiteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBoundAnyLink()
  {
    return boundAnyLinkEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBoundAnyLink_Name()
  {
    return (EAttribute)boundAnyLinkEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getFreeLink()
  {
    return freeLinkEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getFreeLink_Name()
  {
    return (EAttribute)freeLinkEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getIndexedFreeLink()
  {
    return indexedFreeLinkEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getIndexedFreeLink_Name()
  {
    return (EAttribute)indexedFreeLinkEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getIndexedFreeLink_State()
  {
    return (EAttribute)indexedFreeLinkEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTypedFreeLink()
  {
    return typedFreeLinkEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTypedFreeLink_Name()
  {
    return (EAttribute)typedFreeLinkEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTypedFreeLink_State()
  {
    return (EReference)typedFreeLinkEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getWhatEver()
  {
    return whatEverEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getWhatEver_Name()
  {
    return (EAttribute)whatEverEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBoundLink()
  {
    return boundLinkEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBoundLink_State()
  {
    return (EAttribute)boundLinkEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMultiLink()
  {
    return multiLinkEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMultiLink_States()
  {
    return (EReference)multiLinkEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBoundAnyOfTypeLink()
  {
    return boundAnyOfTypeLinkEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBoundAnyOfTypeLink_LinkAgent()
  {
    return (EReference)boundAnyOfTypeLinkEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBoundAnyOfTypeLink_LinkSite()
  {
    return (EReference)boundAnyOfTypeLinkEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSingleSitePattern()
  {
    return singleSitePatternEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSingleSitePattern_Site()
  {
    return (EReference)singleSitePatternEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSingleSitePattern_LinkState()
  {
    return (EReference)singleSitePatternEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMultiLinkSitePattern()
  {
    return multiLinkSitePatternEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMultiLinkSitePattern_Site()
  {
    return (EReference)multiLinkSitePatternEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMultiLinkSitePattern_LinkState()
  {
    return (EReference)multiLinkSitePatternEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SimSGLFactory getSimSGLFactory()
  {
    return (SimSGLFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    simSGLModelEClass = createEClass(SIM_SGL_MODEL);
    createEReference(simSGLModelEClass, SIM_SGL_MODEL__MODEL);
    createEReference(simSGLModelEClass, SIM_SGL_MODEL__PROPERTIES);

    modelEClass = createEClass(MODEL);
    createEAttribute(modelEClass, MODEL__NAME);

    simSGLPropertyEClass = createEClass(SIM_SGL_PROPERTY);
    createEAttribute(simSGLPropertyEClass, SIM_SGL_PROPERTY__NAME);

    arithmeticValueEClass = createEClass(ARITHMETIC_VALUE);
    createEAttribute(arithmeticValueEClass, ARITHMETIC_VALUE__VALUE);

    stateEClass = createEClass(STATE);
    createEAttribute(stateEClass, STATE__NAME);

    statesEClass = createEClass(STATES);
    createEReference(statesEClass, STATES__STATE);

    siteEClass = createEClass(SITE);
    createEAttribute(siteEClass, SITE__NAME);
    createEReference(siteEClass, SITE__STATES);

    sitesEClass = createEClass(SITES);
    createEReference(sitesEClass, SITES__SITES);

    agentEClass = createEClass(AGENT);
    createEReference(agentEClass, AGENT__SITES);

    patternVariableEClass = createEClass(PATTERN_VARIABLE);
    createEReference(patternVariableEClass, PATTERN_VARIABLE__PATTERN);

    arithmeticVariableEClass = createEClass(ARITHMETIC_VARIABLE);
    createEReference(arithmeticVariableEClass, ARITHMETIC_VARIABLE__VALUE);

    variableEClass = createEClass(VARIABLE);

    linkStateEClass = createEClass(LINK_STATE);
    createEReference(linkStateEClass, LINK_STATE__LINK_STATE);

    boundAnyOfTypeLinkAgentEClass = createEClass(BOUND_ANY_OF_TYPE_LINK_AGENT);
    createEReference(boundAnyOfTypeLinkAgentEClass, BOUND_ANY_OF_TYPE_LINK_AGENT__AGENT);

    boundAnyOfTypeLinkSiteEClass = createEClass(BOUND_ANY_OF_TYPE_LINK_SITE);
    createEReference(boundAnyOfTypeLinkSiteEClass, BOUND_ANY_OF_TYPE_LINK_SITE__SITE);

    siteStateEClass = createEClass(SITE_STATE);
    createEReference(siteStateEClass, SITE_STATE__STATE);

    multiLinkStateEClass = createEClass(MULTI_LINK_STATE);
    createEReference(multiLinkStateEClass, MULTI_LINK_STATE__LINK_STATE);

    sitePatternEClass = createEClass(SITE_PATTERN);
    createEReference(sitePatternEClass, SITE_PATTERN__STATE);

    sitePatternsEClass = createEClass(SITE_PATTERNS);
    createEReference(sitePatternsEClass, SITE_PATTERNS__SITE_PATTERNS);

    validAgentPatternEClass = createEClass(VALID_AGENT_PATTERN);
    createEReference(validAgentPatternEClass, VALID_AGENT_PATTERN__AGENT);
    createEReference(validAgentPatternEClass, VALID_AGENT_PATTERN__SITE_PATTERNS);

    voidAgentPatternEClass = createEClass(VOID_AGENT_PATTERN);
    createEAttribute(voidAgentPatternEClass, VOID_AGENT_PATTERN__PATTERN);

    agentPatternEClass = createEClass(AGENT_PATTERN);

    patternEClass = createEClass(PATTERN);
    createEReference(patternEClass, PATTERN__AGENT_PATTERNS);

    observationEClass = createEClass(OBSERVATION);
    createEReference(observationEClass, OBSERVATION__OBSERVATION_PATTERN);

    numericFromLiteralEClass = createEClass(NUMERIC_FROM_LITERAL);
    createEReference(numericFromLiteralEClass, NUMERIC_FROM_LITERAL__VALUE);

    numericFromVariableEClass = createEClass(NUMERIC_FROM_VARIABLE);
    createEReference(numericFromVariableEClass, NUMERIC_FROM_VARIABLE__VALUE_VAR);

    numericAssignmentEClass = createEClass(NUMERIC_ASSIGNMENT);

    initialEClass = createEClass(INITIAL);
    createEReference(initialEClass, INITIAL__COUNT);
    createEReference(initialEClass, INITIAL__INITIAL_PATTERN);

    assignFromPatternEClass = createEClass(ASSIGN_FROM_PATTERN);
    createEReference(assignFromPatternEClass, ASSIGN_FROM_PATTERN__PATTERN);

    assignFromVariableEClass = createEClass(ASSIGN_FROM_VARIABLE);
    createEReference(assignFromVariableEClass, ASSIGN_FROM_VARIABLE__PATTERN_VAR);

    patternAssignmentEClass = createEClass(PATTERN_ASSIGNMENT);

    ruleVariablesEClass = createEClass(RULE_VARIABLES);
    createEReference(ruleVariablesEClass, RULE_VARIABLES__VARIABLES);

    ruleBodyEClass = createEClass(RULE_BODY);
    createEReference(ruleBodyEClass, RULE_BODY__LHS);
    createEAttribute(ruleBodyEClass, RULE_BODY__OPERATOR);
    createEReference(ruleBodyEClass, RULE_BODY__RHS);
    createEReference(ruleBodyEClass, RULE_BODY__VARIABLES);

    ruleEClass = createEClass(RULE);
    createEReference(ruleEClass, RULE__RULE);

    iterationsEClass = createEClass(ITERATIONS);

    timeEClass = createEClass(TIME);

    populationEClass = createEClass(POPULATION);
    createEReference(populationEClass, POPULATION__PA);

    terminationConditionEClass = createEClass(TERMINATION_CONDITION);
    createEAttribute(terminationConditionEClass, TERMINATION_CONDITION__VALUE);

    terminateEClass = createEClass(TERMINATE);
    createEReference(terminateEClass, TERMINATE__CONDITION);

    singleSiteEClass = createEClass(SINGLE_SITE);

    multiSiteEClass = createEClass(MULTI_SITE);

    boundAnyLinkEClass = createEClass(BOUND_ANY_LINK);
    createEAttribute(boundAnyLinkEClass, BOUND_ANY_LINK__NAME);

    freeLinkEClass = createEClass(FREE_LINK);
    createEAttribute(freeLinkEClass, FREE_LINK__NAME);

    indexedFreeLinkEClass = createEClass(INDEXED_FREE_LINK);
    createEAttribute(indexedFreeLinkEClass, INDEXED_FREE_LINK__NAME);
    createEAttribute(indexedFreeLinkEClass, INDEXED_FREE_LINK__STATE);

    typedFreeLinkEClass = createEClass(TYPED_FREE_LINK);
    createEAttribute(typedFreeLinkEClass, TYPED_FREE_LINK__NAME);
    createEReference(typedFreeLinkEClass, TYPED_FREE_LINK__STATE);

    whatEverEClass = createEClass(WHAT_EVER);
    createEAttribute(whatEverEClass, WHAT_EVER__NAME);

    boundLinkEClass = createEClass(BOUND_LINK);
    createEAttribute(boundLinkEClass, BOUND_LINK__STATE);

    multiLinkEClass = createEClass(MULTI_LINK);
    createEReference(multiLinkEClass, MULTI_LINK__STATES);

    boundAnyOfTypeLinkEClass = createEClass(BOUND_ANY_OF_TYPE_LINK);
    createEReference(boundAnyOfTypeLinkEClass, BOUND_ANY_OF_TYPE_LINK__LINK_AGENT);
    createEReference(boundAnyOfTypeLinkEClass, BOUND_ANY_OF_TYPE_LINK__LINK_SITE);

    singleSitePatternEClass = createEClass(SINGLE_SITE_PATTERN);
    createEReference(singleSitePatternEClass, SINGLE_SITE_PATTERN__SITE);
    createEReference(singleSitePatternEClass, SINGLE_SITE_PATTERN__LINK_STATE);

    multiLinkSitePatternEClass = createEClass(MULTI_LINK_SITE_PATTERN);
    createEReference(multiLinkSitePatternEClass, MULTI_LINK_SITE_PATTERN__SITE);
    createEReference(multiLinkSitePatternEClass, MULTI_LINK_SITE_PATTERN__LINK_STATE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    agentEClass.getESuperTypes().add(this.getSimSGLProperty());
    patternVariableEClass.getESuperTypes().add(this.getVariable());
    arithmeticVariableEClass.getESuperTypes().add(this.getVariable());
    variableEClass.getESuperTypes().add(this.getSimSGLProperty());
    validAgentPatternEClass.getESuperTypes().add(this.getAgentPattern());
    voidAgentPatternEClass.getESuperTypes().add(this.getAgentPattern());
    observationEClass.getESuperTypes().add(this.getSimSGLProperty());
    numericFromLiteralEClass.getESuperTypes().add(this.getNumericAssignment());
    numericFromVariableEClass.getESuperTypes().add(this.getNumericAssignment());
    initialEClass.getESuperTypes().add(this.getSimSGLProperty());
    assignFromPatternEClass.getESuperTypes().add(this.getPatternAssignment());
    assignFromVariableEClass.getESuperTypes().add(this.getPatternAssignment());
    ruleEClass.getESuperTypes().add(this.getSimSGLProperty());
    iterationsEClass.getESuperTypes().add(this.getTerminationCondition());
    timeEClass.getESuperTypes().add(this.getTerminationCondition());
    populationEClass.getESuperTypes().add(this.getTerminationCondition());
    terminateEClass.getESuperTypes().add(this.getSimSGLProperty());
    singleSiteEClass.getESuperTypes().add(this.getSite());
    multiSiteEClass.getESuperTypes().add(this.getSite());
    boundAnyLinkEClass.getESuperTypes().add(this.getLinkState());
    freeLinkEClass.getESuperTypes().add(this.getLinkState());
    indexedFreeLinkEClass.getESuperTypes().add(this.getLinkState());
    typedFreeLinkEClass.getESuperTypes().add(this.getLinkState());
    whatEverEClass.getESuperTypes().add(this.getLinkState());
    boundLinkEClass.getESuperTypes().add(this.getLinkState());
    multiLinkEClass.getESuperTypes().add(this.getLinkState());
    boundAnyOfTypeLinkEClass.getESuperTypes().add(this.getLinkState());
    singleSitePatternEClass.getESuperTypes().add(this.getSitePattern());
    multiLinkSitePatternEClass.getESuperTypes().add(this.getSitePattern());

    // Initialize classes and features; add operations and parameters
    initEClass(simSGLModelEClass, SimSGLModel.class, "SimSGLModel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSimSGLModel_Model(), this.getModel(), null, "model", null, 0, 1, SimSGLModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSimSGLModel_Properties(), this.getSimSGLProperty(), null, "properties", null, 0, -1, SimSGLModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getModel_Name(), ecorePackage.getEString(), "name", null, 0, 1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(simSGLPropertyEClass, SimSGLProperty.class, "SimSGLProperty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSimSGLProperty_Name(), ecorePackage.getEString(), "name", null, 0, 1, SimSGLProperty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(arithmeticValueEClass, ArithmeticValue.class, "ArithmeticValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getArithmeticValue_Value(), ecorePackage.getEString(), "value", null, 0, 1, ArithmeticValue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stateEClass, State.class, "State", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getState_Name(), ecorePackage.getEString(), "name", null, 0, 1, State.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(statesEClass, States.class, "States", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getStates_State(), this.getState(), null, "state", null, 0, -1, States.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(siteEClass, Site.class, "Site", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSite_Name(), ecorePackage.getEString(), "name", null, 0, 1, Site.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSite_States(), this.getStates(), null, "states", null, 0, 1, Site.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(sitesEClass, Sites.class, "Sites", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSites_Sites(), this.getSite(), null, "sites", null, 0, -1, Sites.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(agentEClass, Agent.class, "Agent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAgent_Sites(), this.getSites(), null, "sites", null, 0, 1, Agent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(patternVariableEClass, PatternVariable.class, "PatternVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPatternVariable_Pattern(), this.getPattern(), null, "pattern", null, 0, 1, PatternVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(arithmeticVariableEClass, ArithmeticVariable.class, "ArithmeticVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getArithmeticVariable_Value(), this.getArithmeticValue(), null, "value", null, 0, 1, ArithmeticVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(variableEClass, Variable.class, "Variable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(linkStateEClass, LinkState.class, "LinkState", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getLinkState_LinkState(), this.getLinkState(), null, "linkState", null, 0, 1, LinkState.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(boundAnyOfTypeLinkAgentEClass, BoundAnyOfTypeLinkAgent.class, "BoundAnyOfTypeLinkAgent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBoundAnyOfTypeLinkAgent_Agent(), this.getAgent(), null, "agent", null, 0, 1, BoundAnyOfTypeLinkAgent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(boundAnyOfTypeLinkSiteEClass, BoundAnyOfTypeLinkSite.class, "BoundAnyOfTypeLinkSite", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBoundAnyOfTypeLinkSite_Site(), this.getSite(), null, "site", null, 0, 1, BoundAnyOfTypeLinkSite.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(siteStateEClass, SiteState.class, "SiteState", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSiteState_State(), this.getState(), null, "state", null, 0, 1, SiteState.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(multiLinkStateEClass, MultiLinkState.class, "MultiLinkState", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMultiLinkState_LinkState(), this.getLinkState(), null, "linkState", null, 0, 1, MultiLinkState.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(sitePatternEClass, SitePattern.class, "SitePattern", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSitePattern_State(), this.getSiteState(), null, "state", null, 0, 1, SitePattern.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(sitePatternsEClass, SitePatterns.class, "SitePatterns", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSitePatterns_SitePatterns(), this.getSitePattern(), null, "sitePatterns", null, 0, -1, SitePatterns.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(validAgentPatternEClass, ValidAgentPattern.class, "ValidAgentPattern", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getValidAgentPattern_Agent(), this.getAgent(), null, "agent", null, 0, 1, ValidAgentPattern.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getValidAgentPattern_SitePatterns(), this.getSitePatterns(), null, "sitePatterns", null, 0, 1, ValidAgentPattern.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(voidAgentPatternEClass, VoidAgentPattern.class, "VoidAgentPattern", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVoidAgentPattern_Pattern(), ecorePackage.getEString(), "pattern", null, 0, 1, VoidAgentPattern.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(agentPatternEClass, AgentPattern.class, "AgentPattern", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(patternEClass, Pattern.class, "Pattern", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPattern_AgentPatterns(), this.getAgentPattern(), null, "agentPatterns", null, 0, -1, Pattern.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(observationEClass, Observation.class, "Observation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getObservation_ObservationPattern(), this.getPatternAssignment(), null, "observationPattern", null, 0, 1, Observation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(numericFromLiteralEClass, NumericFromLiteral.class, "NumericFromLiteral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getNumericFromLiteral_Value(), this.getArithmeticValue(), null, "value", null, 0, 1, NumericFromLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(numericFromVariableEClass, NumericFromVariable.class, "NumericFromVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getNumericFromVariable_ValueVar(), this.getArithmeticVariable(), null, "valueVar", null, 0, 1, NumericFromVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(numericAssignmentEClass, NumericAssignment.class, "NumericAssignment", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(initialEClass, Initial.class, "Initial", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getInitial_Count(), this.getNumericAssignment(), null, "count", null, 0, 1, Initial.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInitial_InitialPattern(), this.getPatternAssignment(), null, "initialPattern", null, 0, 1, Initial.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(assignFromPatternEClass, AssignFromPattern.class, "AssignFromPattern", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAssignFromPattern_Pattern(), this.getPattern(), null, "pattern", null, 0, 1, AssignFromPattern.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(assignFromVariableEClass, AssignFromVariable.class, "AssignFromVariable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAssignFromVariable_PatternVar(), this.getPatternVariable(), null, "patternVar", null, 0, 1, AssignFromVariable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(patternAssignmentEClass, PatternAssignment.class, "PatternAssignment", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(ruleVariablesEClass, RuleVariables.class, "RuleVariables", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRuleVariables_Variables(), this.getNumericAssignment(), null, "variables", null, 0, -1, RuleVariables.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ruleBodyEClass, RuleBody.class, "RuleBody", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRuleBody_Lhs(), this.getPatternAssignment(), null, "lhs", null, 0, 1, RuleBody.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRuleBody_Operator(), ecorePackage.getEString(), "operator", null, 0, 1, RuleBody.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRuleBody_Rhs(), this.getPatternAssignment(), null, "rhs", null, 0, 1, RuleBody.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRuleBody_Variables(), this.getRuleVariables(), null, "variables", null, 0, 1, RuleBody.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ruleEClass, Rule.class, "Rule", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getRule_Rule(), this.getRuleBody(), null, "rule", null, 0, 1, Rule.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(iterationsEClass, Iterations.class, "Iterations", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(timeEClass, Time.class, "Time", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(populationEClass, Population.class, "Population", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPopulation_Pa(), this.getPatternAssignment(), null, "pa", null, 0, 1, Population.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(terminationConditionEClass, TerminationCondition.class, "TerminationCondition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTerminationCondition_Value(), ecorePackage.getEString(), "value", null, 0, 1, TerminationCondition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(terminateEClass, Terminate.class, "Terminate", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTerminate_Condition(), this.getTerminationCondition(), null, "condition", null, 0, 1, Terminate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(singleSiteEClass, SingleSite.class, "SingleSite", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(multiSiteEClass, MultiSite.class, "MultiSite", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(boundAnyLinkEClass, BoundAnyLink.class, "BoundAnyLink", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBoundAnyLink_Name(), ecorePackage.getEString(), "name", null, 0, 1, BoundAnyLink.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(freeLinkEClass, FreeLink.class, "FreeLink", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFreeLink_Name(), ecorePackage.getEString(), "name", null, 0, 1, FreeLink.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(indexedFreeLinkEClass, IndexedFreeLink.class, "IndexedFreeLink", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIndexedFreeLink_Name(), ecorePackage.getEString(), "name", null, 0, 1, IndexedFreeLink.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getIndexedFreeLink_State(), ecorePackage.getEString(), "state", null, 0, 1, IndexedFreeLink.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(typedFreeLinkEClass, TypedFreeLink.class, "TypedFreeLink", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTypedFreeLink_Name(), ecorePackage.getEString(), "name", null, 0, 1, TypedFreeLink.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTypedFreeLink_State(), this.getAgent(), null, "state", null, 0, 1, TypedFreeLink.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(whatEverEClass, WhatEver.class, "WhatEver", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getWhatEver_Name(), ecorePackage.getEString(), "name", null, 0, 1, WhatEver.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(boundLinkEClass, BoundLink.class, "BoundLink", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBoundLink_State(), ecorePackage.getEString(), "state", null, 0, 1, BoundLink.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(multiLinkEClass, MultiLink.class, "MultiLink", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMultiLink_States(), this.getLinkState(), null, "states", null, 0, -1, MultiLink.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(boundAnyOfTypeLinkEClass, BoundAnyOfTypeLink.class, "BoundAnyOfTypeLink", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBoundAnyOfTypeLink_LinkAgent(), this.getBoundAnyOfTypeLinkAgent(), null, "linkAgent", null, 0, 1, BoundAnyOfTypeLink.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBoundAnyOfTypeLink_LinkSite(), this.getBoundAnyOfTypeLinkSite(), null, "linkSite", null, 0, 1, BoundAnyOfTypeLink.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(singleSitePatternEClass, SingleSitePattern.class, "SingleSitePattern", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getSingleSitePattern_Site(), this.getSingleSite(), null, "site", null, 0, 1, SingleSitePattern.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSingleSitePattern_LinkState(), this.getLinkState(), null, "linkState", null, 0, 1, SingleSitePattern.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(multiLinkSitePatternEClass, MultiLinkSitePattern.class, "MultiLinkSitePattern", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMultiLinkSitePattern_Site(), this.getMultiSite(), null, "site", null, 0, 1, MultiLinkSitePattern.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMultiLinkSitePattern_LinkState(), this.getMultiLinkState(), null, "linkState", null, 0, 1, MultiLinkSitePattern.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //SimSGLPackageImpl
