/**
 * generated by Xtext 2.16.0
 */
package org.simsg.simsgl.simSGL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.simsg.simsgl.simSGL.Agent;
import org.simsg.simsgl.simSGL.SimSGLPackage;
import org.simsg.simsgl.simSGL.SitePatterns;
import org.simsg.simsgl.simSGL.ValidAgentPattern;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Valid Agent Pattern</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.simsg.simsgl.simSGL.impl.ValidAgentPatternImpl#getAgent <em>Agent</em>}</li>
 *   <li>{@link org.simsg.simsgl.simSGL.impl.ValidAgentPatternImpl#getSitePatterns <em>Site Patterns</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ValidAgentPatternImpl extends AgentPatternImpl implements ValidAgentPattern
{
  /**
   * The cached value of the '{@link #getAgent() <em>Agent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAgent()
   * @generated
   * @ordered
   */
  protected Agent agent;

  /**
   * The cached value of the '{@link #getSitePatterns() <em>Site Patterns</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSitePatterns()
   * @generated
   * @ordered
   */
  protected SitePatterns sitePatterns;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ValidAgentPatternImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SimSGLPackage.Literals.VALID_AGENT_PATTERN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Agent getAgent()
  {
    if (agent != null && agent.eIsProxy())
    {
      InternalEObject oldAgent = (InternalEObject)agent;
      agent = (Agent)eResolveProxy(oldAgent);
      if (agent != oldAgent)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, SimSGLPackage.VALID_AGENT_PATTERN__AGENT, oldAgent, agent));
      }
    }
    return agent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Agent basicGetAgent()
  {
    return agent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAgent(Agent newAgent)
  {
    Agent oldAgent = agent;
    agent = newAgent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimSGLPackage.VALID_AGENT_PATTERN__AGENT, oldAgent, agent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SitePatterns getSitePatterns()
  {
    return sitePatterns;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSitePatterns(SitePatterns newSitePatterns, NotificationChain msgs)
  {
    SitePatterns oldSitePatterns = sitePatterns;
    sitePatterns = newSitePatterns;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SimSGLPackage.VALID_AGENT_PATTERN__SITE_PATTERNS, oldSitePatterns, newSitePatterns);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSitePatterns(SitePatterns newSitePatterns)
  {
    if (newSitePatterns != sitePatterns)
    {
      NotificationChain msgs = null;
      if (sitePatterns != null)
        msgs = ((InternalEObject)sitePatterns).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SimSGLPackage.VALID_AGENT_PATTERN__SITE_PATTERNS, null, msgs);
      if (newSitePatterns != null)
        msgs = ((InternalEObject)newSitePatterns).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SimSGLPackage.VALID_AGENT_PATTERN__SITE_PATTERNS, null, msgs);
      msgs = basicSetSitePatterns(newSitePatterns, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SimSGLPackage.VALID_AGENT_PATTERN__SITE_PATTERNS, newSitePatterns, newSitePatterns));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SimSGLPackage.VALID_AGENT_PATTERN__SITE_PATTERNS:
        return basicSetSitePatterns(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SimSGLPackage.VALID_AGENT_PATTERN__AGENT:
        if (resolve) return getAgent();
        return basicGetAgent();
      case SimSGLPackage.VALID_AGENT_PATTERN__SITE_PATTERNS:
        return getSitePatterns();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SimSGLPackage.VALID_AGENT_PATTERN__AGENT:
        setAgent((Agent)newValue);
        return;
      case SimSGLPackage.VALID_AGENT_PATTERN__SITE_PATTERNS:
        setSitePatterns((SitePatterns)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SimSGLPackage.VALID_AGENT_PATTERN__AGENT:
        setAgent((Agent)null);
        return;
      case SimSGLPackage.VALID_AGENT_PATTERN__SITE_PATTERNS:
        setSitePatterns((SitePatterns)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SimSGLPackage.VALID_AGENT_PATTERN__AGENT:
        return agent != null;
      case SimSGLPackage.VALID_AGENT_PATTERN__SITE_PATTERNS:
        return sitePatterns != null;
    }
    return super.eIsSet(featureID);
  }

} //ValidAgentPatternImpl
