<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xsi:schemaLocation="http://www.eclipse.org/emf/2002/Ecore java://org.eclipse.emf.ecore.EcorePackage"
    name="Goldbeter_Koshland" nsURI="platform:/resource/org.simsg.container/generated/Goldbeter_Koshland"
    nsPrefix="Goldbeter_Koshland">
  <eClassifiers xmi:type="ecore:EClass" name="K" instanceTypeName="K" eSuperTypes="ecore:EClass http://www.simsg.container.org/container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="K_a1" eType="ecore:EClass http://www.simsg.container.org/container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="P" instanceTypeName="P" eSuperTypes="ecore:EClass http://www.simsg.container.org/container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="P_a2" eType="ecore:EClass http://www.simsg.container.org/container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="T" instanceTypeName="T" eSuperTypes="ecore:EClass http://www.simsg.container.org/container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="T_x" eType="ecore:EClass http://www.simsg.container.org/container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="T_x_us" eType="#//us"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="T_x_ps" eType="#//ps"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="T_y" eType="ecore:EClass http://www.simsg.container.org/container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="T_y_us" eType="#//us"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="T_y_ps" eType="#//ps"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="us" eSuperTypes="ecore:EClass http://www.simsg.container.org/container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="ps" eSuperTypes="ecore:EClass http://www.simsg.container.org/container#//State"/>
</ecore:EPackage>
