/**
 * generated by Xtext 2.12.0
 */
package biochemsimulation.reactionrules.reactionRules;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exact Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link biochemsimulation.reactionrules.reactionRules.ExactLink#getLinkAgent <em>Link Agent</em>}</li>
 *   <li>{@link biochemsimulation.reactionrules.reactionRules.ExactLink#getLinkSite <em>Link Site</em>}</li>
 * </ul>
 *
 * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage#getExactLink()
 * @model
 * @generated
 */
public interface ExactLink extends LinkState
{
  /**
   * Returns the value of the '<em><b>Link Agent</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Link Agent</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link Agent</em>' containment reference.
   * @see #setLinkAgent(ExactLinkAgent)
   * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage#getExactLink_LinkAgent()
   * @model containment="true"
   * @generated
   */
  ExactLinkAgent getLinkAgent();

  /**
   * Sets the value of the '{@link biochemsimulation.reactionrules.reactionRules.ExactLink#getLinkAgent <em>Link Agent</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link Agent</em>' containment reference.
   * @see #getLinkAgent()
   * @generated
   */
  void setLinkAgent(ExactLinkAgent value);

  /**
   * Returns the value of the '<em><b>Link Site</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Link Site</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link Site</em>' containment reference.
   * @see #setLinkSite(ExactLinkSite)
   * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage#getExactLink_LinkSite()
   * @model containment="true"
   * @generated
   */
  ExactLinkSite getLinkSite();

  /**
   * Sets the value of the '{@link biochemsimulation.reactionrules.reactionRules.ExactLink#getLinkSite <em>Link Site</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link Site</em>' containment reference.
   * @see #getLinkSite()
   * @generated
   */
  void setLinkSite(ExactLinkSite value);

} // ExactLink
