/**
 * generated by Xtext 2.12.0
 */
package biochemsimulation.reactionrules.reactionRules;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Initial</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link biochemsimulation.reactionrules.reactionRules.Initial#getCount <em>Count</em>}</li>
 *   <li>{@link biochemsimulation.reactionrules.reactionRules.Initial#getInitialPattern <em>Initial Pattern</em>}</li>
 * </ul>
 *
 * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage#getInitial()
 * @model
 * @generated
 */
public interface Initial extends ReactionProperty
{
  /**
   * Returns the value of the '<em><b>Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Count</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Count</em>' attribute.
   * @see #setCount(String)
   * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage#getInitial_Count()
   * @model
   * @generated
   */
  String getCount();

  /**
   * Sets the value of the '{@link biochemsimulation.reactionrules.reactionRules.Initial#getCount <em>Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Count</em>' attribute.
   * @see #getCount()
   * @generated
   */
  void setCount(String value);

  /**
   * Returns the value of the '<em><b>Initial Pattern</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Initial Pattern</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initial Pattern</em>' containment reference.
   * @see #setInitialPattern(PatternAssignment)
   * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage#getInitial_InitialPattern()
   * @model containment="true"
   * @generated
   */
  PatternAssignment getInitialPattern();

  /**
   * Sets the value of the '{@link biochemsimulation.reactionrules.reactionRules.Initial#getInitialPattern <em>Initial Pattern</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initial Pattern</em>' containment reference.
   * @see #getInitialPattern()
   * @generated
   */
  void setInitialPattern(PatternAssignment value);

} // Initial
