/**
 * generated by Xtext 2.12.0
 */
package biochemsimulation.reactionrules.reactionRules;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Numeric Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage#getNumericAssignment()
 * @model
 * @generated
 */
public interface NumericAssignment extends EObject
{
} // NumericAssignment
