/**
 * generated by Xtext 2.16.0
 */
package biochemsimulation.reactionrules.reactionRules;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pattern</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link biochemsimulation.reactionrules.reactionRules.Pattern#getAgentPatterns <em>Agent Patterns</em>}</li>
 * </ul>
 *
 * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage#getPattern()
 * @model
 * @generated
 */
public interface Pattern extends EObject
{
  /**
   * Returns the value of the '<em><b>Agent Patterns</b></em>' containment reference list.
   * The list contents are of type {@link biochemsimulation.reactionrules.reactionRules.AgentPattern}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Agent Patterns</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Agent Patterns</em>' containment reference list.
   * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage#getPattern_AgentPatterns()
   * @model containment="true"
   * @generated
   */
  EList<AgentPattern> getAgentPatterns();

} // Pattern
