/**
 * generated by Xtext 2.12.0
 */
package biochemsimulation.reactionrules.reactionRules;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage
 * @generated
 */
public interface ReactionRulesFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ReactionRulesFactory eINSTANCE = biochemsimulation.reactionrules.reactionRules.impl.ReactionRulesFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Reaction Rule Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reaction Rule Model</em>'.
   * @generated
   */
  ReactionRuleModel createReactionRuleModel();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Reaction Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reaction Property</em>'.
   * @generated
   */
  ReactionProperty createReactionProperty();

  /**
   * Returns a new object of class '<em>Arithmetic Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arithmetic Value</em>'.
   * @generated
   */
  ArithmeticValue createArithmeticValue();

  /**
   * Returns a new object of class '<em>State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State</em>'.
   * @generated
   */
  State createState();

  /**
   * Returns a new object of class '<em>States</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>States</em>'.
   * @generated
   */
  States createStates();

  /**
   * Returns a new object of class '<em>Site</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Site</em>'.
   * @generated
   */
  Site createSite();

  /**
   * Returns a new object of class '<em>Sites</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sites</em>'.
   * @generated
   */
  Sites createSites();

  /**
   * Returns a new object of class '<em>Agent</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Agent</em>'.
   * @generated
   */
  Agent createAgent();

  /**
   * Returns a new object of class '<em>Pattern Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pattern Variable</em>'.
   * @generated
   */
  PatternVariable createPatternVariable();

  /**
   * Returns a new object of class '<em>Arithmetic Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arithmetic Variable</em>'.
   * @generated
   */
  ArithmeticVariable createArithmeticVariable();

  /**
   * Returns a new object of class '<em>Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable</em>'.
   * @generated
   */
  Variable createVariable();

  /**
   * Returns a new object of class '<em>Link State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Link State</em>'.
   * @generated
   */
  LinkState createLinkState();

  /**
   * Returns a new object of class '<em>Bound Any Of Type Link Agent</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bound Any Of Type Link Agent</em>'.
   * @generated
   */
  BoundAnyOfTypeLinkAgent createBoundAnyOfTypeLinkAgent();

  /**
   * Returns a new object of class '<em>Bound Any Of Type Link Site</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bound Any Of Type Link Site</em>'.
   * @generated
   */
  BoundAnyOfTypeLinkSite createBoundAnyOfTypeLinkSite();

  /**
   * Returns a new object of class '<em>Site State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Site State</em>'.
   * @generated
   */
  SiteState createSiteState();

  /**
   * Returns a new object of class '<em>Site Pattern</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Site Pattern</em>'.
   * @generated
   */
  SitePattern createSitePattern();

  /**
   * Returns a new object of class '<em>Site Patterns</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Site Patterns</em>'.
   * @generated
   */
  SitePatterns createSitePatterns();

  /**
   * Returns a new object of class '<em>Valid Agent Pattern</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Valid Agent Pattern</em>'.
   * @generated
   */
  ValidAgentPattern createValidAgentPattern();

  /**
   * Returns a new object of class '<em>Void Agent Pattern</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Void Agent Pattern</em>'.
   * @generated
   */
  VoidAgentPattern createVoidAgentPattern();

  /**
   * Returns a new object of class '<em>Agent Pattern</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Agent Pattern</em>'.
   * @generated
   */
  AgentPattern createAgentPattern();

  /**
   * Returns a new object of class '<em>Pattern</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pattern</em>'.
   * @generated
   */
  Pattern createPattern();

  /**
   * Returns a new object of class '<em>Observation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Observation</em>'.
   * @generated
   */
  Observation createObservation();

  /**
   * Returns a new object of class '<em>Numeric From Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Numeric From Literal</em>'.
   * @generated
   */
  NumericFromLiteral createNumericFromLiteral();

  /**
   * Returns a new object of class '<em>Numeric From Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Numeric From Variable</em>'.
   * @generated
   */
  NumericFromVariable createNumericFromVariable();

  /**
   * Returns a new object of class '<em>Numeric Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Numeric Assignment</em>'.
   * @generated
   */
  NumericAssignment createNumericAssignment();

  /**
   * Returns a new object of class '<em>Initial</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial</em>'.
   * @generated
   */
  Initial createInitial();

  /**
   * Returns a new object of class '<em>Assign From Pattern</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assign From Pattern</em>'.
   * @generated
   */
  AssignFromPattern createAssignFromPattern();

  /**
   * Returns a new object of class '<em>Assign From Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Assign From Variable</em>'.
   * @generated
   */
  AssignFromVariable createAssignFromVariable();

  /**
   * Returns a new object of class '<em>Pattern Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pattern Assignment</em>'.
   * @generated
   */
  PatternAssignment createPatternAssignment();

  /**
   * Returns a new object of class '<em>Rule Variables</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule Variables</em>'.
   * @generated
   */
  RuleVariables createRuleVariables();

  /**
   * Returns a new object of class '<em>Rule Body</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule Body</em>'.
   * @generated
   */
  RuleBody createRuleBody();

  /**
   * Returns a new object of class '<em>Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule</em>'.
   * @generated
   */
  Rule createRule();

  /**
   * Returns a new object of class '<em>Iterations</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Iterations</em>'.
   * @generated
   */
  Iterations createIterations();

  /**
   * Returns a new object of class '<em>Time</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Time</em>'.
   * @generated
   */
  Time createTime();

  /**
   * Returns a new object of class '<em>Population</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Population</em>'.
   * @generated
   */
  Population createPopulation();

  /**
   * Returns a new object of class '<em>Termination Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Termination Condition</em>'.
   * @generated
   */
  TerminationCondition createTerminationCondition();

  /**
   * Returns a new object of class '<em>Terminate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Terminate</em>'.
   * @generated
   */
  Terminate createTerminate();

  /**
   * Returns a new object of class '<em>Bound Any Link</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bound Any Link</em>'.
   * @generated
   */
  BoundAnyLink createBoundAnyLink();

  /**
   * Returns a new object of class '<em>Free Link</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Free Link</em>'.
   * @generated
   */
  FreeLink createFreeLink();

  /**
   * Returns a new object of class '<em>What Ever</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>What Ever</em>'.
   * @generated
   */
  WhatEver createWhatEver();

  /**
   * Returns a new object of class '<em>Bound Link</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bound Link</em>'.
   * @generated
   */
  BoundLink createBoundLink();

  /**
   * Returns a new object of class '<em>Bound Any Of Type Link</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bound Any Of Type Link</em>'.
   * @generated
   */
  BoundAnyOfTypeLink createBoundAnyOfTypeLink();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ReactionRulesPackage getReactionRulesPackage();

} //ReactionRulesFactory
