/**
 * generated by Xtext 2.12.0
 */
package biochemsimulation.reactionrules.reactionRules;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link biochemsimulation.reactionrules.reactionRules.Rule#getLhs <em>Lhs</em>}</li>
 *   <li>{@link biochemsimulation.reactionrules.reactionRules.Rule#getRhs <em>Rhs</em>}</li>
 *   <li>{@link biochemsimulation.reactionrules.reactionRules.Rule#getVariables <em>Variables</em>}</li>
 * </ul>
 *
 * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends ReactionProperty
{
  /**
   * Returns the value of the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lhs</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lhs</em>' containment reference.
   * @see #setLhs(Pattern)
   * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage#getRule_Lhs()
   * @model containment="true"
   * @generated
   */
  Pattern getLhs();

  /**
   * Sets the value of the '{@link biochemsimulation.reactionrules.reactionRules.Rule#getLhs <em>Lhs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lhs</em>' containment reference.
   * @see #getLhs()
   * @generated
   */
  void setLhs(Pattern value);

  /**
   * Returns the value of the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rhs</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rhs</em>' containment reference.
   * @see #setRhs(Pattern)
   * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage#getRule_Rhs()
   * @model containment="true"
   * @generated
   */
  Pattern getRhs();

  /**
   * Sets the value of the '{@link biochemsimulation.reactionrules.reactionRules.Rule#getRhs <em>Rhs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rhs</em>' containment reference.
   * @see #getRhs()
   * @generated
   */
  void setRhs(Pattern value);

  /**
   * Returns the value of the '<em><b>Variables</b></em>' reference list.
   * The list contents are of type {@link biochemsimulation.reactionrules.reactionRules.Variable}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variables</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' reference list.
   * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage#getRule_Variables()
   * @model
   * @generated
   */
  EList<Variable> getVariables();

} // Rule
