/**
 * generated by Xtext 2.12.0
 */
package biochemsimulation.reactionrules.reactionRules;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Semi Link</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage#getSemiLink()
 * @model
 * @generated
 */
public interface SemiLink extends LinkState
{
} // SemiLink
