/**
 * generated by Xtext 2.16.0
 */
package biochemsimulation.reactionrules.reactionRules;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Site</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see biochemsimulation.reactionrules.reactionRules.ReactionRulesPackage#getSingleSite()
 * @model
 * @generated
 */
public interface SingleSite extends Site
{
} // SingleSite
