<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xsi:schemaLocation="http://www.eclipse.org/emf/2002/Ecore java://org.eclipse.emf.ecore.EcorePackage"
    name="PatternMatchingTest" nsURI="platform:/resource/SimSG.Container/generated/PatternMatchingTest"
    nsPrefix="PatternMatchingTest">
  <eClassifiers xmi:type="ecore:EClass" name="A1" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="A1_x" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A1_y" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="B1" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="B1_x" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B1_z" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="A2" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="A2_x" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A2_y" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="B2" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="B2_x" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B2_z" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="C1" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="C1_v" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="C1_w" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="A3" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="A3_x" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A3_y" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="B3" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="B3_x" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B3_z" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="A4" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="A4_x" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A4_x_p" eType="#//p"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A4_x_q" eType="#//q"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A4_y" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A4_y_m" eType="#//m"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A4_y_n" eType="#//n"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="p" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="q" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="m" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="n" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="B4" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="B4_x" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B4_x_a" eType="#//a"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B4_x_b" eType="#//b"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B4_z" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B4_z_o" eType="#//o"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B4_z_p" eType="#//p"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="a" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="b" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="o" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="C4" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="C4_v" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="C4_w" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="A5" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="A5_x" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A5_x_u" eType="#//u"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A5_x_v" eType="#//v"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A5_y" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="u" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="v" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="B5" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="B5_w" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B5_z" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B5_z_p" eType="#//p"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B5_z_q" eType="#//q"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="A6" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="A6_x" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A6_x_u" eType="#//u"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A6_x_v" eType="#//v"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A6_y" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A6_z" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A6_z_r" eType="#//r"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A6_z_t" eType="#//t"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="r" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="t" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="B6" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="B6_u" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B6_v" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B6_v_l" eType="#//l"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B6_v_m" eType="#//m"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B6_v_n" eType="#//n"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B6_w" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B6_w_r" eType="#//r"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B6_w_s" eType="#//s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B6_w_t" eType="#//t"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="l" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="s" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="C3" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="C3_a" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="C3_a_i" eType="#//i"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="C3_a_j" eType="#//j"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="C3_b" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="C3_b_e" eType="#//e"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="C3_b_f" eType="#//f"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="C3_b_g" eType="#//g"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="C3_c" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="i" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="j" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="e" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="f" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="g" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="A7" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="A7_w" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A7_w_a" eType="#//a"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A7_w_b" eType="#//b"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A7_x" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A7_x_c" eType="#//c"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A7_x_d" eType="#//d"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="c" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="d" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="B7" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="B7_y" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B7_y_e" eType="#//e"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B7_y_f" eType="#//f"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B7_z" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B7_z_g" eType="#//g"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="B7_z_h" eType="#//h"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="h" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="A8" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="A8_x" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A8_y" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="A9" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="A9_x" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="A9_y" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="mA" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="mA_x" upperBound="-1" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="mB" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="mB_y" upperBound="-1" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="mC" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="mC_z" upperBound="-1" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="mD" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="mD_a" upperBound="-1" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="mD_b" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="mD_c" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="mQ" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="mQ_b" upperBound="-1" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="mP" eSuperTypes="ecore:EClass http://www.Container.SimSG.org/Container#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="mP_c" upperBound="-1" eType="ecore:EClass http://www.Container.SimSG.org/Container#//Agent"/>
  </eClassifiers>
</ecore:EPackage>
