/*
 * generated by Xtext 2.16.0
 */
package org.simsg.simsgl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.simsg.simsgl.ide.contentassist.antlr.internal.InternalSimSGLParser;
import org.simsg.simsgl.services.SimSGLGrammarAccess;

public class SimSGLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(SimSGLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, SimSGLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getSimSGLPropertyAccess().getAlternatives(), "rule__SimSGLProperty__Alternatives");
			builder.put(grammarAccess.getScientificFloatAccess().getAlternatives_5(), "rule__ScientificFloat__Alternatives_5");
			builder.put(grammarAccess.getArithmeticTypeAccess().getAlternatives(), "rule__ArithmeticType__Alternatives");
			builder.put(grammarAccess.getSiteAccess().getAlternatives(), "rule__Site__Alternatives");
			builder.put(grammarAccess.getVariableAccess().getAlternatives(), "rule__Variable__Alternatives");
			builder.put(grammarAccess.getMultiLinkAccess().getStatesAlternatives_1_0_0(), "rule__MultiLink__StatesAlternatives_1_0_0");
			builder.put(grammarAccess.getMultiLinkAccess().getStatesAlternatives_1_1_1_0(), "rule__MultiLink__StatesAlternatives_1_1_1_0");
			builder.put(grammarAccess.getLinkStateAccess().getLinkStateAlternatives_2_0(), "rule__LinkState__LinkStateAlternatives_2_0");
			builder.put(grammarAccess.getMultiLinkStateAccess().getLinkStateAlternatives_2_0(), "rule__MultiLinkState__LinkStateAlternatives_2_0");
			builder.put(grammarAccess.getSitePatternAccess().getAlternatives(), "rule__SitePattern__Alternatives");
			builder.put(grammarAccess.getAgentPatternAccess().getAlternatives(), "rule__AgentPattern__Alternatives");
			builder.put(grammarAccess.getNumericAssignmentAccess().getAlternatives(), "rule__NumericAssignment__Alternatives");
			builder.put(grammarAccess.getPatternAssignmentAccess().getAlternatives(), "rule__PatternAssignment__Alternatives");
			builder.put(grammarAccess.getRuleBodyAccess().getAlternatives(), "rule__RuleBody__Alternatives");
			builder.put(grammarAccess.getTerminationConditionAccess().getAlternatives(), "rule__TerminationCondition__Alternatives");
			builder.put(grammarAccess.getSimSGLModelAccess().getGroup(), "rule__SimSGLModel__Group__0");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getFloatAccess().getGroup(), "rule__Float__Group__0");
			builder.put(grammarAccess.getScientificFloatAccess().getGroup(), "rule__ScientificFloat__Group__0");
			builder.put(grammarAccess.getSignedIntegerAccess().getGroup(), "rule__SignedInteger__Group__0");
			builder.put(grammarAccess.getStatesAccess().getGroup(), "rule__States__Group__0");
			builder.put(grammarAccess.getStatesAccess().getGroup_1(), "rule__States__Group_1__0");
			builder.put(grammarAccess.getStatesAccess().getGroup_1_2(), "rule__States__Group_1_2__0");
			builder.put(grammarAccess.getSingleSiteAccess().getGroup(), "rule__SingleSite__Group__0");
			builder.put(grammarAccess.getMultiSiteAccess().getGroup(), "rule__MultiSite__Group__0");
			builder.put(grammarAccess.getSitesAccess().getGroup(), "rule__Sites__Group__0");
			builder.put(grammarAccess.getSitesAccess().getGroup_1(), "rule__Sites__Group_1__0");
			builder.put(grammarAccess.getSitesAccess().getGroup_1_2(), "rule__Sites__Group_1_2__0");
			builder.put(grammarAccess.getAgentAccess().getGroup(), "rule__Agent__Group__0");
			builder.put(grammarAccess.getPatternVariableAccess().getGroup(), "rule__PatternVariable__Group__0");
			builder.put(grammarAccess.getArithmeticVariableAccess().getGroup(), "rule__ArithmeticVariable__Group__0");
			builder.put(grammarAccess.getBoundAnyLinkAccess().getGroup(), "rule__BoundAnyLink__Group__0");
			builder.put(grammarAccess.getFreeLinkAccess().getGroup(), "rule__FreeLink__Group__0");
			builder.put(grammarAccess.getIndexedFreeLinkAccess().getGroup(), "rule__IndexedFreeLink__Group__0");
			builder.put(grammarAccess.getTypedFreeLinkAccess().getGroup(), "rule__TypedFreeLink__Group__0");
			builder.put(grammarAccess.getWhatEverAccess().getGroup(), "rule__WhatEver__Group__0");
			builder.put(grammarAccess.getBoundLinkAccess().getGroup(), "rule__BoundLink__Group__0");
			builder.put(grammarAccess.getMultiLinkAccess().getGroup(), "rule__MultiLink__Group__0");
			builder.put(grammarAccess.getMultiLinkAccess().getGroup_1(), "rule__MultiLink__Group_1__0");
			builder.put(grammarAccess.getMultiLinkAccess().getGroup_1_1(), "rule__MultiLink__Group_1_1__0");
			builder.put(grammarAccess.getBoundAnyOfTypeLinkAgentAccess().getGroup(), "rule__BoundAnyOfTypeLinkAgent__Group__0");
			builder.put(grammarAccess.getBoundAnyOfTypeLinkSiteAccess().getGroup(), "rule__BoundAnyOfTypeLinkSite__Group__0");
			builder.put(grammarAccess.getBoundAnyOfTypeLinkAccess().getGroup(), "rule__BoundAnyOfTypeLink__Group__0");
			builder.put(grammarAccess.getSiteStateAccess().getGroup(), "rule__SiteState__Group__0");
			builder.put(grammarAccess.getLinkStateAccess().getGroup(), "rule__LinkState__Group__0");
			builder.put(grammarAccess.getMultiLinkStateAccess().getGroup(), "rule__MultiLinkState__Group__0");
			builder.put(grammarAccess.getSingleSitePatternAccess().getGroup(), "rule__SingleSitePattern__Group__0");
			builder.put(grammarAccess.getMultiLinkSitePatternAccess().getGroup(), "rule__MultiLinkSitePattern__Group__0");
			builder.put(grammarAccess.getSitePatternsAccess().getGroup(), "rule__SitePatterns__Group__0");
			builder.put(grammarAccess.getSitePatternsAccess().getGroup_2(), "rule__SitePatterns__Group_2__0");
			builder.put(grammarAccess.getSitePatternsAccess().getGroup_2_1(), "rule__SitePatterns__Group_2_1__0");
			builder.put(grammarAccess.getValidAgentPatternAccess().getGroup(), "rule__ValidAgentPattern__Group__0");
			builder.put(grammarAccess.getPatternAccess().getGroup(), "rule__Pattern__Group__0");
			builder.put(grammarAccess.getPatternAccess().getGroup_2(), "rule__Pattern__Group_2__0");
			builder.put(grammarAccess.getPatternAccess().getGroup_2_1(), "rule__Pattern__Group_2_1__0");
			builder.put(grammarAccess.getObservationAccess().getGroup(), "rule__Observation__Group__0");
			builder.put(grammarAccess.getInitialAccess().getGroup(), "rule__Initial__Group__0");
			builder.put(grammarAccess.getRuleVariablesAccess().getGroup(), "rule__RuleVariables__Group__0");
			builder.put(grammarAccess.getRuleVariablesAccess().getGroup_1(), "rule__RuleVariables__Group_1__0");
			builder.put(grammarAccess.getUnidirectionalRuleAccess().getGroup(), "rule__UnidirectionalRule__Group__0");
			builder.put(grammarAccess.getBidirectionalRuleAccess().getGroup(), "rule__BidirectionalRule__Group__0");
			builder.put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
			builder.put(grammarAccess.getIterationsAccess().getGroup(), "rule__Iterations__Group__0");
			builder.put(grammarAccess.getTimeAccess().getGroup(), "rule__Time__Group__0");
			builder.put(grammarAccess.getPopulationAccess().getGroup(), "rule__Population__Group__0");
			builder.put(grammarAccess.getTerminateAccess().getGroup(), "rule__Terminate__Group__0");
			builder.put(grammarAccess.getSimSGLModelAccess().getModelAssignment_0(), "rule__SimSGLModel__ModelAssignment_0");
			builder.put(grammarAccess.getSimSGLModelAccess().getPropertiesAssignment_1(), "rule__SimSGLModel__PropertiesAssignment_1");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_1(), "rule__Model__NameAssignment_1");
			builder.put(grammarAccess.getArithmeticValueAccess().getValueAssignment(), "rule__ArithmeticValue__ValueAssignment");
			builder.put(grammarAccess.getStateAccess().getNameAssignment(), "rule__State__NameAssignment");
			builder.put(grammarAccess.getStatesAccess().getStateAssignment_1_1(), "rule__States__StateAssignment_1_1");
			builder.put(grammarAccess.getStatesAccess().getStateAssignment_1_2_1(), "rule__States__StateAssignment_1_2_1");
			builder.put(grammarAccess.getSingleSiteAccess().getNameAssignment_1(), "rule__SingleSite__NameAssignment_1");
			builder.put(grammarAccess.getSingleSiteAccess().getStatesAssignment_2(), "rule__SingleSite__StatesAssignment_2");
			builder.put(grammarAccess.getMultiSiteAccess().getNameAssignment_2(), "rule__MultiSite__NameAssignment_2");
			builder.put(grammarAccess.getMultiSiteAccess().getStatesAssignment_3(), "rule__MultiSite__StatesAssignment_3");
			builder.put(grammarAccess.getSitesAccess().getSitesAssignment_1_1(), "rule__Sites__SitesAssignment_1_1");
			builder.put(grammarAccess.getSitesAccess().getSitesAssignment_1_2_1(), "rule__Sites__SitesAssignment_1_2_1");
			builder.put(grammarAccess.getAgentAccess().getNameAssignment_1(), "rule__Agent__NameAssignment_1");
			builder.put(grammarAccess.getAgentAccess().getSitesAssignment_2(), "rule__Agent__SitesAssignment_2");
			builder.put(grammarAccess.getPatternVariableAccess().getNameAssignment_1(), "rule__PatternVariable__NameAssignment_1");
			builder.put(grammarAccess.getPatternVariableAccess().getPatternAssignment_3(), "rule__PatternVariable__PatternAssignment_3");
			builder.put(grammarAccess.getArithmeticVariableAccess().getNameAssignment_1(), "rule__ArithmeticVariable__NameAssignment_1");
			builder.put(grammarAccess.getArithmeticVariableAccess().getValueAssignment_3(), "rule__ArithmeticVariable__ValueAssignment_3");
			builder.put(grammarAccess.getBoundAnyLinkAccess().getNameAssignment_1(), "rule__BoundAnyLink__NameAssignment_1");
			builder.put(grammarAccess.getFreeLinkAccess().getNameAssignment_1(), "rule__FreeLink__NameAssignment_1");
			builder.put(grammarAccess.getIndexedFreeLinkAccess().getNameAssignment_1(), "rule__IndexedFreeLink__NameAssignment_1");
			builder.put(grammarAccess.getIndexedFreeLinkAccess().getStateAssignment_3(), "rule__IndexedFreeLink__StateAssignment_3");
			builder.put(grammarAccess.getTypedFreeLinkAccess().getNameAssignment_1(), "rule__TypedFreeLink__NameAssignment_1");
			builder.put(grammarAccess.getTypedFreeLinkAccess().getStateAssignment_3(), "rule__TypedFreeLink__StateAssignment_3");
			builder.put(grammarAccess.getWhatEverAccess().getNameAssignment_1(), "rule__WhatEver__NameAssignment_1");
			builder.put(grammarAccess.getBoundLinkAccess().getStateAssignment_1(), "rule__BoundLink__StateAssignment_1");
			builder.put(grammarAccess.getMultiLinkAccess().getStatesAssignment_1_0(), "rule__MultiLink__StatesAssignment_1_0");
			builder.put(grammarAccess.getMultiLinkAccess().getStatesAssignment_1_1_1(), "rule__MultiLink__StatesAssignment_1_1_1");
			builder.put(grammarAccess.getBoundAnyOfTypeLinkAgentAccess().getAgentAssignment_1(), "rule__BoundAnyOfTypeLinkAgent__AgentAssignment_1");
			builder.put(grammarAccess.getBoundAnyOfTypeLinkSiteAccess().getSiteAssignment_1(), "rule__BoundAnyOfTypeLinkSite__SiteAssignment_1");
			builder.put(grammarAccess.getBoundAnyOfTypeLinkAccess().getLinkAgentAssignment_1(), "rule__BoundAnyOfTypeLink__LinkAgentAssignment_1");
			builder.put(grammarAccess.getBoundAnyOfTypeLinkAccess().getLinkSiteAssignment_3(), "rule__BoundAnyOfTypeLink__LinkSiteAssignment_3");
			builder.put(grammarAccess.getSiteStateAccess().getStateAssignment_2(), "rule__SiteState__StateAssignment_2");
			builder.put(grammarAccess.getLinkStateAccess().getLinkStateAssignment_2(), "rule__LinkState__LinkStateAssignment_2");
			builder.put(grammarAccess.getMultiLinkStateAccess().getLinkStateAssignment_2(), "rule__MultiLinkState__LinkStateAssignment_2");
			builder.put(grammarAccess.getSingleSitePatternAccess().getSiteAssignment_1(), "rule__SingleSitePattern__SiteAssignment_1");
			builder.put(grammarAccess.getSingleSitePatternAccess().getStateAssignment_2(), "rule__SingleSitePattern__StateAssignment_2");
			builder.put(grammarAccess.getSingleSitePatternAccess().getLinkStateAssignment_3(), "rule__SingleSitePattern__LinkStateAssignment_3");
			builder.put(grammarAccess.getMultiLinkSitePatternAccess().getSiteAssignment_1(), "rule__MultiLinkSitePattern__SiteAssignment_1");
			builder.put(grammarAccess.getMultiLinkSitePatternAccess().getStateAssignment_2(), "rule__MultiLinkSitePattern__StateAssignment_2");
			builder.put(grammarAccess.getMultiLinkSitePatternAccess().getLinkStateAssignment_3(), "rule__MultiLinkSitePattern__LinkStateAssignment_3");
			builder.put(grammarAccess.getSitePatternsAccess().getSitePatternsAssignment_2_0(), "rule__SitePatterns__SitePatternsAssignment_2_0");
			builder.put(grammarAccess.getSitePatternsAccess().getSitePatternsAssignment_2_1_1(), "rule__SitePatterns__SitePatternsAssignment_2_1_1");
			builder.put(grammarAccess.getValidAgentPatternAccess().getAgentAssignment_1(), "rule__ValidAgentPattern__AgentAssignment_1");
			builder.put(grammarAccess.getValidAgentPatternAccess().getSitePatternsAssignment_2(), "rule__ValidAgentPattern__SitePatternsAssignment_2");
			builder.put(grammarAccess.getVoidAgentPatternAccess().getPatternAssignment(), "rule__VoidAgentPattern__PatternAssignment");
			builder.put(grammarAccess.getPatternAccess().getAgentPatternsAssignment_2_0(), "rule__Pattern__AgentPatternsAssignment_2_0");
			builder.put(grammarAccess.getPatternAccess().getAgentPatternsAssignment_2_1_1(), "rule__Pattern__AgentPatternsAssignment_2_1_1");
			builder.put(grammarAccess.getObservationAccess().getNameAssignment_1(), "rule__Observation__NameAssignment_1");
			builder.put(grammarAccess.getObservationAccess().getObservationPatternAssignment_2(), "rule__Observation__ObservationPatternAssignment_2");
			builder.put(grammarAccess.getNumericFromLiteralAccess().getValueAssignment(), "rule__NumericFromLiteral__ValueAssignment");
			builder.put(grammarAccess.getNumericFromVariableAccess().getValueVarAssignment(), "rule__NumericFromVariable__ValueVarAssignment");
			builder.put(grammarAccess.getInitialAccess().getNameAssignment_1(), "rule__Initial__NameAssignment_1");
			builder.put(grammarAccess.getInitialAccess().getCountAssignment_2(), "rule__Initial__CountAssignment_2");
			builder.put(grammarAccess.getInitialAccess().getInitialPatternAssignment_3(), "rule__Initial__InitialPatternAssignment_3");
			builder.put(grammarAccess.getAssignFromPatternAccess().getPatternAssignment(), "rule__AssignFromPattern__PatternAssignment");
			builder.put(grammarAccess.getAssignFromVariableAccess().getPatternVarAssignment(), "rule__AssignFromVariable__PatternVarAssignment");
			builder.put(grammarAccess.getRuleVariablesAccess().getVariablesAssignment_0(), "rule__RuleVariables__VariablesAssignment_0");
			builder.put(grammarAccess.getRuleVariablesAccess().getVariablesAssignment_1_1(), "rule__RuleVariables__VariablesAssignment_1_1");
			builder.put(grammarAccess.getUnidirectionalRuleAccess().getLhsAssignment_0(), "rule__UnidirectionalRule__LhsAssignment_0");
			builder.put(grammarAccess.getUnidirectionalRuleAccess().getOperatorAssignment_1(), "rule__UnidirectionalRule__OperatorAssignment_1");
			builder.put(grammarAccess.getUnidirectionalRuleAccess().getRhsAssignment_2(), "rule__UnidirectionalRule__RhsAssignment_2");
			builder.put(grammarAccess.getUnidirectionalRuleAccess().getVariablesAssignment_5(), "rule__UnidirectionalRule__VariablesAssignment_5");
			builder.put(grammarAccess.getBidirectionalRuleAccess().getLhsAssignment_0(), "rule__BidirectionalRule__LhsAssignment_0");
			builder.put(grammarAccess.getBidirectionalRuleAccess().getOperatorAssignment_1(), "rule__BidirectionalRule__OperatorAssignment_1");
			builder.put(grammarAccess.getBidirectionalRuleAccess().getRhsAssignment_2(), "rule__BidirectionalRule__RhsAssignment_2");
			builder.put(grammarAccess.getBidirectionalRuleAccess().getVariablesAssignment_5(), "rule__BidirectionalRule__VariablesAssignment_5");
			builder.put(grammarAccess.getRuleAccess().getNameAssignment_1(), "rule__Rule__NameAssignment_1");
			builder.put(grammarAccess.getRuleAccess().getRuleAssignment_2(), "rule__Rule__RuleAssignment_2");
			builder.put(grammarAccess.getIterationsAccess().getValueAssignment_2(), "rule__Iterations__ValueAssignment_2");
			builder.put(grammarAccess.getTimeAccess().getValueAssignment_2(), "rule__Time__ValueAssignment_2");
			builder.put(grammarAccess.getPopulationAccess().getPaAssignment_1(), "rule__Population__PaAssignment_1");
			builder.put(grammarAccess.getPopulationAccess().getValueAssignment_4(), "rule__Population__ValueAssignment_4");
			builder.put(grammarAccess.getTerminateAccess().getNameAssignment_1(), "rule__Terminate__NameAssignment_1");
			builder.put(grammarAccess.getTerminateAccess().getConditionAssignment_2(), "rule__Terminate__ConditionAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private SimSGLGrammarAccess grammarAccess;

	@Override
	protected InternalSimSGLParser createParser() {
		InternalSimSGLParser result = new InternalSimSGLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SimSGLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimSGLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
