<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="reactioncontainer" nsURI="http://www.reactioncontainer.biochemsimulation.org/reactioncontainer"
    nsPrefix="reactioncontainer">
  <eClassifiers xsi:type="ecore:EClass" name="ReactionContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="simAgent" upperBound="-1"
        eType="#//SimAgent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simLinkStates" upperBound="-1"
        eType="#//SimLinkState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimAgent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simSites" upperBound="-1"
        eType="#//SimSite" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimSite">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simSiteState" eType="#//SimSiteState"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simAgent" lowerBound="1"
        eType="#//SimAgent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simLinkState" eType="#//SimLinkState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimSiteState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimLinkState" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="simSite1" lowerBound="1"
        eType="#//SimSite"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimBound" eSuperTypes="#//SimLinkState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="simSite2" lowerBound="1"
        eType="#//SimSite"/>
  </eClassifiers>
</ecore:EPackage>
